global:
  cattle:
    systemDefaultRegistry: "registry-stg.vestack.sbuxcf.net"

aiAgent:
  image:
    repository: rancher/rancher-ai-agent
    tag: v1.0.0-rc.3
    pullPolicy: IfNotPresent
mcp:
  readOnly: false
  image:
    repository: rancher/rancher-ai-mcp
    tag: v1.0.0
    pullPolicy: IfNotPresent

ollamaLlmModel: ""
geminiLlmModel: ""
openaiLlmModel: ""
bedrockLlmModel: ""
ollamaUrl: ""
googleApiKey:
openaiApiKey:
openaiUrl:
awsBedrock:
  bearerToken:
  region:
activeLlm: # ollama, gemini, openai, bedrock
langfuseSecretKey:
langfusePublicKey:
langfuseHost:
storage:
  enabled: false
  connectionString: ""
probes:
  startup:
    initialDelaySeconds: 5
    periodSeconds: 2
    failureThreshold: 10
  liveness:
    initialDelaySeconds: 0
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 2
insecureSkipTls: false
seLinux:
  enabled: false
llmMock:
  enabled: false
  url: ""
log:
  level: info
