name: Publish Helm Chart

on:
  push:
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io
  CHART_PATH: ./chart/agent

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Get version from Git tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Update Chart.yaml with new version
        run: |
          echo "Updating chart to version $VERSION"
          sed -i "s/^version: .*/version: $VERSION/" $CHART_PATH/Chart.yaml
          sed -i "s/^appVersion: .*/appVersion: \"$VERSION\"/" $CHART_PATH/Chart.yaml

          echo "--- Chart.yaml after update ---"
          cat $CHART_PATH/Chart.yaml
          echo "------------------------------"
        env:
          VERSION: ${{ env.VERSION }}
          CHART_PATH: ${{ env.CHART_PATH }} 

      - name: Install Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5

      - name: Log in to GHCR
        run: echo $GITHUB_TOKEN | helm registry login $REGISTRY -u $ACTOR --password-stdin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          REGISTRY: ${{ env.REGISTRY }}
          ACTOR: ${{ github.actor }}
           
      - name: Package Helm chart
        run: helm package $CHART_PATH --destination .helm-packages
        env:
          CHART_PATH: ${{ env.CHART_PATH }} 

      - name: Push chart to GHCR OCI registry
        run: helm push .helm-packages/rancher-ai-agent-$VERSION.tgz oci://$REGISTRY/$REPOSITORY/charts
        env:
          REGISTRY: ${{ env.REGISTRY }}
          VERSION: ${{ env.VERSION }}
          REPOSITORY: ${{ github.repository }}
